#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /T ps_3_0 /E main /Fh
//    E:\360ports\enablers\sdl360\shaders\blit_ps.h /Vn g_blit_ps
//    E:\360ports\enablers\sdl360\shaders\blit_ps.hlsl
//
//
// Parameters:
//
//   sampler2D fb;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   fb           s0       1
//

// Shader type: pixel 

xps_3_0
defconst fb, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
// PsExportColorCount=1
// PsSampleControl=centers

dcl_texcoord r0.xy


    exec
    tfetch2D r0, r0.xy, tf0
    alloc colors
    exece
    mov oC0, r0

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_blit_ps[] =
{
    0x102a1100, 0x000000a4, 0x0000003c, 0x00000000, 0x00000024, 0x00000000, 
    0x00000080, 0x00000000, 0x00000000, 0x00000058, 0x0000001c, 0x0000004b, 
    0xffff0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000044, 0x00000030, 
    0x00030000, 0x00010000, 0x00000034, 0x00000000, 0x666200ab, 0x0004000c, 
    0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 0x2e302e32, 
    0x31323536, 0x2e3000ab, 0x00000000, 0x0000003c, 0x10000000, 0x00000004, 
    0x00000000, 0x00000821, 0x00010001, 0x00000001, 0x00003050, 0x00011002, 
    0x00001200, 0xc4000000, 0x00001003, 0x00002200, 0x00000000, 0x10080001, 
    0x1f1ff688, 0x00004000, 0xc80f8000, 0x00000000, 0xe2000000, 0x00000000, 
    0x00000000, 0x00000000
};
